// <auto-generated />
namespace CheckPoint.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GameIdNullReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameIdNullReview));
        
        string IMigrationMetadata.Id
        {
            get { return "202010082043547_GameIdNullReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
